host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv
overlays_dir: overlays

runtime_environments:
  - name: ps-nlp
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

  - name: ps-nlp-pytorch
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

  - name: ps-nlp-tensorflow
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

  - name: ps-nlp-tensorflow-gpu
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

managers:
  - name: update
    disallow:
    - ps-nlp-tensorflow-gpu
    - ps-nlp-pytorch
    configuration:
      labels: [bot]
  - name: thoth-advise
    allow:
    - ps-nlp
    configuration:
      labels: [bot]
#   - name: info
#   - name: version
#     configuration:
#       assignees:
#         - sesheta
#       labels: [bot]
#       changelog_file: true
